"""Dialogue generation — routed THROUGH cognee recall (Option B).

Instead of a separate LLM provider call, the NPC's line is generated by cognee's
recall in generation mode (`only_context=False`) with the persona+stance as the
system prompt. That means *all* inference goes through cognee, so in Cognee Cloud
mode it is billed to your Cognee credits and no separate LLM key is required.

The model only supplies the WORDS. The emotion is authored per node (story.py), and
flags/relationships/branching are decided by gamestate. The generated line is run
through the locked-fact guardrail; on any failure (empty, leak, recall error, no
key/credits) we serve the node's authored fallback line.
"""
import config  # noqa: F401  -- loads .env + configures cognee on import
from memory import LOCK, first_answer, recall_for_npc
from npcs import NPCS
from validators import validate_text


async def generate_line(npc_id: str, node: dict, state: dict) -> dict:
    """Phrase the NPC's current story stance via cognee recall; fall back to authored."""
    npc = NPCS[npc_id]
    rel = state["relationships"][npc_id]
    emotion = node.get("emotion", "neutral")

    system = (
        f"{npc['persona']}\n\n"
        f"Your current situation (do not quote this verbatim): {node['stance']}\n"
        f"Your feelings toward the player right now: trust {rel['trust']}/100, "
        f"suspicion {rel['suspicion']}/100.\n"
        "Answer in the first person in 30-45 words, using ONLY what you actually "
        "remember from your memories. Do not reveal anything you have not been told."
    )

    try:
        async with LOCK:
            results = await recall_for_npc(
                npc_id, node["stance"], context_only=False, system_prompt=system
            )
        line = validate_text(first_answer(results), state)
        return {"npcLine": line, "emotion": emotion, "source": "cognee"}
    except Exception as e:  # noqa: BLE001 -- any failure => safe authored fallback
        return {"npcLine": node["fallback"], "emotion": emotion,
                "source": "fallback", "fallbackReason": f"{type(e).__name__}: {str(e)[:120]}"}


async def generate_response(npc_id: str, player_input: str) -> dict:
    """Legacy /dialogue/respond — free-form NPC reply, also via cognee recall."""
    if npc_id not in NPCS:
        raise KeyError(npc_id)
    npc = NPCS[npc_id]
    async with LOCK:
        results = await recall_for_npc(npc_id, player_input, context_only=False)
    return {
        "npc_id": npc_id,
        "name": npc["name"],
        "npc_line": first_answer(results) or "…",
        "source": "cognee",
    }
